baseURL = 'https://alles-standard.social/'
languageCode = 'en-us'
title = 'Alles Standard'
theme = 'ananke'

[menu]
  [[menu.main]]
    weight = 1
    name = "Events"
    url = "/events/"
    title = "Events"
  [[menu.main]]
    weight = 2
    name = "Discord"
    url = "/discord/"
    title = "Discord"
[params]
  site_logo = "images/logo.png"

timezone = "Europe/Berlin"
