name: Daily Data Update

on:
  schedule:
    # Run daily at 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch: # Allow manual triggering for testing

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    # Only run on main branch to avoid conflicts
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute data collection script
        run: ./collect.sh

      - name: Check for changes
        id: check_changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          if git diff --staged --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in data files"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in data files"
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git commit -m "Automated data update [skip ci]"
          git push